!PARAMETERS
rndnumbersPerSeed: 100000
#Remover completamente e seção seeds para geração automatica de seeds
#Caso informado n seeds será executado n simulações
#Caso não informado seeds sera executado 5 simulações
seeds:
- 8

arrivals: 
   Senha: 1.0

queues: 
   Senha: 
      servers: 1
      minArrival: 1.0
      maxArrival: 5.0
      minService: 0.08
      maxService: 1
   Atendimento: 
      servers: 3
      capacity: 10
      minService: 5.0
      maxService: 15.0
   Financeiro: 
      servers: 2
      capacity: 10
      minService: 5.0
      maxService: 25.0

network: 
-  source: Senha
   target: Atendimento
   probability: 0.8
-  source: Senha
   target: Financeiro
   probability: 0.2
-  source: Atendimento
   target: Financeiro
   probability: 0.3
-  source: Financeiro
   target: Atendimento
   probability: 0.5
